### PR TITLE
Background changing - fading in and out

### PR DESCRIPTION
**Pull request by apg30**
uses CSS transitions (for fade)  and javascript (to change image).

### CODE REVIEW

**Review by camieac — APPROVED** [review]
Looking good :+1:

**Comment by camieac** [comment]
I've left the branch as is, just in case you still need it. Otherwise, just delete it

**Comment by apg30** [comment]
@camieac 
First image disappears then goes to white on  http://www2.macs.hw.ac.uk/~cac30/. 
Works as expected on localhost (on same branch).
I think it's because either the web hook is not working or production version does not have the images.

**Comment by camieac** [comment]
See Issue #14 , the relative image URIs don't work

Simple fix would be to set urls in js to:
```
var backgrounds = new Array(
    'url(/img/backgrounds/01.jpg)'
  , 'url(/img/backgrounds/02.jpg)'
  , 'url(/img/backgrounds/03.jpg)'
  , 'url(/img/backgrounds/04.jpg)'
  , 'url(/img/backgrounds/05.jpg)'
  , 'url(/img/backgrounds/06.jpg)'
  , 'url(/img/backgrounds/08.jpg)'
  , 'url(/img/backgrounds/10.jpg)'
  , 'url(/img/backgrounds/11.jpg)'
  , 'url(/img/backgrounds/12.jpg)'
);
```
I tried that on my local server and it still worked, not tested on cac30. You can see problem if you look at the browser console.

**Pull request merged**
